Rename assert -> nofail
To try and get around the fact that for some reason the assert method
name triggers a weird compilation failure that I don't want to debug.

For the record, here is the compilation failure:

In file included from include/miniz.h:479,
                 from include/miniz.c:27,
                 from debug.cpp:17:
debug.cpp:150:10: error: expected unqualified-id before ‘static_cast’
  150 |     void assert() const {
      |          ^~~~~~
debug.cpp:150:10: error: expected ‘)’ before ‘static_cast’
  150 |     void assert() const {
      |          ^~~~~~
debug.cpp: In function ‘auto mapassert(auto:47, const auto:48&)’:
debug.cpp:171:9: error: expected unqualified-id before ‘(’ token
  171 |     res.assert();
      |         ^~~~~~
debug.cpp:171:9: error: expected primary-expression before ‘)’ token
  171 |     res.assert();
      |         ^~~~~~

This is probably caused by some half-assed macro I will not bother to
track.